[2022-09-27 17:27:30,771] werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[2022-09-27 17:27:30,771] werkzeug - INFO - [33mPress CTRL+C to quit[0m
[2022-09-27 17:28:19,172] app - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "app.py", line 11, in index
    raise Exception('we are testing custom exception')
Exception: we are testing custom exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Music\iNeuron ML projects\005\project005\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\HP\Music\iNeuron ML projects\005\project005\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\HP\Music\iNeuron ML projects\005\project005\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\HP\Music\iNeuron ML projects\005\project005\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "app.py", line 14, in index
    logging.info(housing.error_massage)
AttributeError: 'HousingException' object has no attribute 'error_massage'
[2022-09-27 17:28:19,180] werkzeug - INFO - 127.0.0.1 - - [27/Sep/2022 17:28:19] "[35m[1mGET / HTTP/1.1[0m" 500 -
